Games/Models/ErrorViewModel.cs
using System;

namespace Games.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Games/Areas/Player/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Games.Models;

namespace Games.Controllers
{
    [Area("Player")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Games/Areas/Player/Controllers/MemoryGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Games.Areas.Player.Controllers
{
    public class MemoryGameController : Controller
    {
        [Area("Player")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Games/Areas/Player/Controllers/WhackAMoleGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Games.Areas.Player.Controllers
{
    public class WhackAMoleGameController : Controller
    {
        [Area("Player")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Games/Areas/Player/Views/GuessTheNumber/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="resultParas">
    <p class="guesses"></p>
    <p class="lastResult"></p>
    <p class="lowOrHi"></p>
</div>

<label for="guessField">Enter a guess: </label>
<input type="text" id="guessField" class="guessField">
<input type="submit" value="Submit guess" class="guessSubmit">

@section Scripts {
    <script>

        let randomNumber = Math.floor(Math.random() * 100) + 1;

        const guesses = document.querySelector('.guesses');
        const lastResult = document.querySelector('.lastResult');
        const lowOrHi = document.querySelector('.lowOrHi');

        const guessSubmit = document.querySelector('.guessSubmit');
        guessSubmit.addEventListener('click', checkGuess);

        const guessField = document.querySelector('.guessField');

        let guessCount = 1;
        let resetButton;

        function checkGuess() {
            let userGuess = Number(guessField.value);
            if (guessCount === 1) {
                guesses.textContent = 'Previous guesses: ';
            }
            guesses.textContent += userGuess + ' ';

            if (userGuess === randomNumber) {
                lastResult.textContent = 'Congratulations! You got it right!';
                lastResult.style.backgroundColor = 'green';
                lowOrHi.textContent = '';
                setGameOver();
            } else if (guessCount === 10) {
                lastResult.textContent = '!!!GAME OVER!!!';
                setGameOver();
            } else {
                lastResult.textContent = 'Wrong!';
                lastResult.style.backgroundColor = 'red';
                if (userGuess < randomNumber) {
                    lowOrHi.textContent = 'Last guess was too low!';
                } else if (userGuess > randomNumber) {
                    lowOrHi.textContent = 'Last guess was too high!';
                }
            }

            guessCount++;
            guessField.value = '';
            guessField.focus();
        }

        function setGameOver() {
            guessField.disabled = true;
            guessSubmit.disabled = true;
            resetButton = document.createElement('button');
            resetButton.textContent = 'Start new game';
            document.body.append(resetButton);
            resetButton.addEventListener('click', resetGame);
        }

        function resetGame() {
            guessCount = 1;

            const resetParas = document.querySelectorAll('.resultParas p');
            for (let i = 0; i < resetParas.length; i++) {
                resetParas[i].textContent = '';
            }

            resetButton.parentNode.removeChild(resetButton);

            guessField.disabled = false;
            guessSubmit.disabled = false;
            guessField.value = '';
            guessField.focus();

            lastResult.style.backgroundColor = 'white';

            randomNumber = Math.floor(Math.random() * 100) + 1;
        }

    </script>
}

Games/Areas/Player/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Games/Areas/Player/Views/MemoryGame/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Memorio</h1>

<h3>Score: <span id="result"></span></h3>

<div class="grid">
</div>


@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            //cards
            const cardArray = [
                {
                    name: 'A',
                    img: '/images/memoryGame/A.jpg'
                },
                {
                    name: 'A',
                    img: '/images/memoryGame/A.jpg'
                },
                {
                    name: 'B',
                    img: '/images/memoryGame/B.jpg'
                },
                {
                    name: 'B',
                    img: '/images/memoryGame/B.jpg'
                },
                {
                    name: 'C',
                    img: '/images/memoryGame/C.jpg'
                },
                {
                    name: 'C',
                    img: '/images/memoryGame/C.jpg'
                },
                {
                    name: 'D',
                    img: '/images/memoryGame/D.jpg'
                },
                {
                    name: 'D',
                    img: '/images/memoryGame/D.jpg'
                },
                {
                    name: 'E',
                    img: '/images/memoryGame/E.jpg'
                },
                {
                    name: 'E',
                    img: '/images/memoryGame/E.jpg'
                },
                {
                    name: 'F',
                    img: '/images/memoryGame/F.jpg'
                },
                {
                    name: 'F',
                    img: '/images/memoryGame/F.jpg'
                },
                {
                    name: 'G',
                    img: '/images/memoryGame/G.jpg'
                },
                {
                    name: 'G',
                    img: '/images/memoryGame/G.jpg'
                },
                {
                    name: 'H',
                    img: '/images/memoryGame/H.jpg'
                },
                {
                    name: 'H',
                    img: '/images/memoryGame/H.jpg'
                },
                {
                    name: 'I',
                    img: '/images/memoryGame/I.jpg'
                },
                {
                    name: 'I',
                    img: '/images/memoryGame/I.jpg'
                },
                {
                    name: 'Z',
                    img: '/images/memoryGame/Z.jpg'
                },
                {
                    name: 'Z',
                    img: '/images/memoryGame/Z.jpg'
                }
            ]

            //RANDOMIZE
            cardArray.sort(() => 0.5 - Math.random());


            //BOARD
            const grid = document.querySelector('.grid');

            const resultDisplay = document.querySelector("#result");
            let cardsChosen = [];
            let cardsChosenId = [];
            let cardsWon = [];

            function createBoard() {
                for (let i = 0; i < cardArray.length; i++) {
                    var card = document.createElement('img');
                    card.setAttribute("src", "/images/memoryGame/blank.png");
                    card.setAttribute("style", "max-width:20%");
                    card.setAttribute("class", "m-2");
                    card.setAttribute('data-id', i);
                    card.addEventListener('click', flipCard);
                    grid.appendChild(card);
                }
            }

            //check for matches
            function checkForMatch() {
                var cards = document.querySelectorAll('img')
                const optionOneId = cardsChosenId[0]
                const optionTwoId = cardsChosenId[1]

                if (optionOneId == optionTwoId) {
                    cards[optionOneId].setAttribute('src', '/images/memoryGame/blank.png')
                    cards[optionTwoId].setAttribute('src', '/images/memoryGame/blank.png')
                    alert('You have clicked the same image!')
                }
                else if (cardsChosen[0] === cardsChosen[1]) {
                    alert('You found a match')
                    cards[optionOneId].setAttribute('src', '/images/memoryGame/white.jpg')
                    cards[optionTwoId].setAttribute('src', '/images/memoryGame/white.jpg')

                    cards[optionOneId].removeEventListener('click', flipCard)
                    cards[optionTwoId].removeEventListener('click', flipCard)
                    cardsWon.push(cardsChosen)
                } else {
                    cards[optionOneId].setAttribute('src', '/images/memoryGame/blank.png')
                    cards[optionTwoId].setAttribute('src', '/images/memoryGame/blank.png')
                    alert('Sorry, try again')
                }
                cardsChosen = []
                cardsChosenId = []
                resultDisplay.textContent = cardsWon.length
                if (cardsWon.length === cardArray.length / 2) {
                    resultDisplay.textContent = 'Congratulations! You found them all!'
                }
            }

            //flip card
            function flipCard() {
                var cardId = this.getAttribute('data-id')
                cardsChosen.push(cardArray[cardId].name)
                cardsChosenId.push(cardId)
                this.setAttribute('src', cardArray[cardId].img)

                if (cardsChosen.length === 2) {
                    setTimeout(checkForMatch, 500)
                }
            }

            createBoard();

        })
    </script>
}

Games/Areas/Player/Views/WhackAMoleGame/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Whack a Mole!</h1>

<h2>Your Score:</h2>
<h2 id="score">0</h2>

<h2>Time Left:</h2>
<h2 id="time-left">60</h2>

<div class="gridMole">

</div>


@section Scripts {
    <script>


        $(document).ready(function () {

            const sqaureBoard = 9;

            function createBoard() {
                for (let i = 0; i < sqaureBoard; i++) {

                    jQuery("<div/>", {
                        id: `${i}`,
                        "class": 'square'
                    }).appendTo(".gridMole");
                }
            }

            createBoard();    

            const square = document.querySelectorAll('.square')
            const mole = document.querySelectorAll('.mole')
            const timeLeft = document.querySelector('#time-left')
            let score = document.querySelector('#score')

            let result = 0
            let currentTime = timeLeft.textContent

            function randomSquare() {
                square.forEach(className => {
                    className.classList.remove('mole')
                })
                let randomPosition = square[Math.floor(Math.random() * 9)]
                randomPosition.classList.add('mole')

                //assign the id of the randomPosition to hitPosition for us to use later
                hitPosition = randomPosition.id
            }

            square.forEach(id => {
                id.addEventListener('mouseup', () => {
                    if (id.id === hitPosition) {
                        result = result + 1
                        score.textContent = result
                        hitPosition = null
                    }
                })
            })


            function moveMole() {
                let timerId = null
                timerId = setInterval(randomSquare, 500)
            }

            moveMole()


            function countDown() {
                currentTime--
                timeLeft.textContent = currentTime

                if (currentTime === 0) {
                    clearInterval(timerId)
                    alert('GAME OVER! Your final score is' + result)
                }
            }

            let timerId = setInterval(countDown, 1000)

        });                

    </script>
}

Games/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Games</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gam(m)y</a>

                <div class="btn-group navbar-nav">
                    <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Games
                    </button>
                    <div class="dropdown-menu">
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="MemoryGame" asp-action="Index">Memio</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="WhackAMoleGame" asp-action="Index">Whack A Mole</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="ConnectFourGame" asp-action="Index">Connect The Dots</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="SnakeGame" asp-action="Index">Snake</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="SpaceInvadersGame" asp-action="Index">Space Invaders</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="FroggerGame" asp-action="Index">Frogger</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="TetrisGame" asp-action="Index">Tetris</a>
                        <a class="nav-link text-dark dropdown-item" asp-area="Player" asp-controller="GuessTheNumber" asp-action="Index">Guessio</a>

                    </div>
                </div>


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Games - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>